# Generated by Django 4.1.7 on 2023-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('datetime', models.TextField()),
            ],
        ),
    ]
