version: "3.8"
services:
  emotidev:
    build:
      context: https://github.com/kobemaristela/EmotiCoach.git#:/backend/deployment/docker
    command: python manage.py runserver 0.0.0.0:1617
    ports:
      - 1617:1617
    env_file:
      - ../configuration/.env.dev
    depends_on:
      - db_dev

  db_dev:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../configuration/.env.dev

volumes:
  postgres_data:
