# Generated by Django 4.1.3 on 2023-02-16 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.BooleanField()),
                ('tricep', models.BooleanField()),
                ('bicep', models.BooleanField()),
                ('shoulder', models.BooleanField()),
                ('upper_back', models.BooleanField()),
                ('lower_back', models.BooleanField()),
                ('quadricep', models.BooleanField()),
                ('glute', models.BooleanField()),
                ('calve', models.BooleanField()),
                ('abdominal', models.BooleanField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workout.activity')),
            ],
        ),
    ]
