# Generated by Django 4.1.7 on 2023-05-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_bound', models.FloatField()),
                ('lower_bound', models.FloatField()),
            ],
        ),
    ]
