# Generated by Django 4.1.7 on 2023-05-02 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='id',
        ),
        migrations.AddField(
            model_name='parameters',
            name='auth_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
