# Generated by Django 4.1.7 on 2023-04-26 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.icon'),
        ),
    ]
