# Generated by Django 4.1.7 on 2023-04-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.icon'),
        ),
    ]
