# Generated by Django 4.1.7 on 2023-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='sleep',
            field=models.FloatField(),
        ),
    ]
