# Generated by Django 4.1.7 on 2023-04-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='channel',
            new_name='topic',
        ),
    ]
