version: "3.8"
services:
  django:
    build:
      context: https://github.com/kobemaristela/EmotiCoach.git#:/backend/deployment
    command: gunicorn emoticoach.wsgi:application --bind  0.0.0.0:1616
    ports:
      - 1616:1616
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

volumes:
  postgres_data:
