# Pull base image - alpine alternative
FROM python:3.11-slim-bullseye

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy dbchecker
COPY ./dbchecker.sh .
RUN sed -i 's/\r$//g' /usr/src/app/dbchecker.sh
RUN chmod +x /usr/src/app/dbchecker.sh

# Copy project
COPY . .

# Run dbchecker
ENTRYPOINT ["/usr/src/app/dbchecker.sh"]