version: "3.8"
services:
  django:
    build:
      context: https://github.com/kobemaristela/EmotiCoach.git#:/backend/deployment
    command: python manage.py runserver 0.0.0.0:1617
    ports:
      - 1617:1617
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.dev

volumes:
  postgres_data:
